### ISSUE TITLE
Import/Export preferences

### ISSUE THREAD

**Issue by 5aji** [Foo-Bear/beartime-web#24]

**Comment by kincaidoneil** [comment]
What do you mean?

**Comment by 5aji** [comment]
Export the JSON settings, for lunches and names. Add an import feature to follow through. Just a thought, though. A step between browser-dependent and user-dependent.

**Comment by kincaidoneil** [comment]
Gotcha. I don't think it'd be worth the effort for most users, though. Probably the more important use case for syncing/portability of the preferences would be between someone's laptop and phone, since not many people use multiple browsers on a regular basis. But given the setup is so quick (just entering classes and lunches), even a Google sign-in or something for syncing settings might not actually save anyone time. It'd also add unnecessary clutter to the UI for a lesser used feature.
