### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by 5aji** [Foo-Bear/beartime-web#57]
The code looks alright but isn't leveraging the full power of vue. We should abstract blocks to a vue component, maybe use vue-router to add a settings page and the week stored as a url param. Also it is bad code practice to get _every_ schedule on launch, I still think dynamic-loading is the way to go.

**Comment by kincaidoneil** [comment]
1. I haven't committed my new code yet. There is a specific Block component.
2. The idea behind the design is to keep it simple enough so that a settings page isn't necessary. As for using vue-router just to store the week as a URL parameter, I considered it, but a) I don't think it provides much utility for users to persist what week they're on between reloads since they probably won't switch days/weeks very often, and it may even harm the user experience since reloading won't automatically jump to today, and b) because there is now both a day and week view, it'd necessitate another container component for weeks (adding unnecessary boilerplate) and have a url like `week/2017-02-17`, which just makes it kinda messy. I think there's another reason I didn't go that route too (no pun intended lol), but that's what I remember.
3. The size of special schedule is so small it's inconsequential versus making a series of five requests back to Firebase, waiting for each to complete and adding latency (which would also add alot of latency switching weeks). If it does get to large, I'd be open to transitioning it to make separate requests or just delete old special schedules.
